
[Names]

# Name of the Results folder that will be created
run_name = TestRun # optional


[Paths]

# Path to csv with the strain info
strains_csv = /mnt/yeast-data/yglaluno1/JoaoCoito/scripts/detect_HGT/strains.csv

# BLAST Database path + name
AlienIndex_BLAST_DB = /mnt/yeast-data/yglaluno1/JoaoCoito/data/blast_db/AlienIndex_BLASTDB/AlienIndex_BLASTDB

# Path to FASTA file used for BLAST databases
AlienIndex_fasta = /mnt/yeast-data/yglaluno1/JoaoCoito/data/blast_db/AlienIndex_DB.fasta

# BLAST Database path + name
Ingroup_BLAST_DB = /mnt/yeast-data/yglaluno1/JoaoCoito/data/blast_db/Saccharomycotina_BLASTDB/Saccharomycotina_BLASTDB

# Path to directory where the Results folder will be created
output_path = /mnt/yeast-data/yglaluno1/JoaoCoito/03_hgt_detection


[Parameters]

# Threshold above which a gene is considered a candidate for HGT
AlienIndex_threshold = 0.05

# Number of threads to be used
# n_threads = 8 # optional (detected)


## 01 - Alien Index BLAST ##

# Alien Index BLAST e-value threshold
evalue = 0.1

# Alien Index BLAST maximum number of target sequences
max_seqs = 500


## 03 - BLAST HGT candidates vs Ingroup DB ##

# Ingroup BLAST e-value threshold
evalue_2nd_blast = 0.1

# Ingroup BLAST maximum number of target sequences
max_seqs_2nd_blast = 500


## 05 - Add top BLAST hits to groups ##

# Number of top BLAST hits to include per HGT candidate
n_top_hits = 100

# Number of ingroup (non-W/S yeasts) hits to include per HGT candidate
n_top_ingroup_hits = 20


## 06 - Align sequences by group ##

# Minimum number of sequences per group
min_numb_seqs = 20

# MAFFT parameters
mafft_parameters = --localpair --maxiterate 1000

# trimAL method
trimal_method = gappyout


## 07 - Build a phylogenetic tree for each group ##

# Length below which alignments are excluded
min_align_len = 0

# IQ-TREE parameters
iqtree_parameters = -m MFP -bb 1000


## 08 - Root and color trees ##

# Group names (should be identical to the tags in the BLAST DBs and FASTA files)
names_groups = YEAST, BACTERIA, FUNGI, WS

# Color that each group will have in the trees (R colors)
color_groups = cyan, olivedrab1, steelblue1, firebrick3
recipient_color = orangered # Candidate HGT color


[Tool Paths]

R_path = /mnt/yeast-data/yglaluno1/miniconda3/envs/R_joaoc/bin/Rscript
blastp_path = /mnt/yeast-data/yeast/miniforge3/envs/BLAST/bin/blastp
mafft_path = /mnt/yeast-data/yeast/miniforge3/envs/OMICS/bin/mafft
trimal_path = /mnt/yeast-data/yglaluno1/miniconda3/envs/mafft_env/bin/trimal
iqtree_path = /mnt/yeast-data/yeast/miniforge3/envs/OMICS/bin/iqtree
